### ISSUE TITLE
"_PIPE_BUF" NameError when trying to add an account

### ISSUE THREAD

**Issue by frdmn** [seveas/git-spindle#130]
Just installed this via `pip`. Whenever I try to add my account:

```
❯ git hub add-account frdmn
GitHub user: frdmn
Traceback (most recent call last):
  File "/usr/local/bin/git-hub", line 11, in <module>
    GitHub().main()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 344, in main
    func(opts)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 357, in add_account
    self.login()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/github.py", line 39, in login
    token = self.config('token')
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 114, in config
    return self.config_secret(key, value)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 139, in config_secret
    credential.fill_noninteractive()
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 483, in fill_noninteractive
    self.communicate('fill', env=env)
  File "/usr/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 499, in communicate
    ret = self.shell.git('-c', 'core.askpass=', 'credential', action, env=env, input=data)
  File "/usr/local/lib/python2.7/site-packages/whelk/__init__.py", line 181, in __call__
    (out, err) = sp.communicate(self.input)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/local/Cellar/python/2.7.12_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1419, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/usr/local/lib/python2.7/site-packages/whelk/subprocess_32.py", line 109, in _communicate_with_select
    chunk = input[input_offset : input_offset + _PIPE_BUF]
NameError: global name '_PIPE_BUF' is not defined
```

---

```
❯ git --version
git version 2.10.0

❯ sw_vers -productVersion
10.12
```

**Comment by seveas** [comment]
That's https://github.com/seveas/whelk/issues/7 again, which I still need to fix.
