### ISSUE TITLE
regression in 'git hub pull-request'

### ISSUE THREAD

**Issue by esc** [seveas/git-spindle#137]
```
% git hub pull-request
Traceback (most recent call last):
  File "/home/esc/bin/git-hub", line 9, in <module>
    from gitspindle.github import GitHub
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/gitspindle/__init__.py", line 1, in <module>
    import gitspindle.monkey
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/gitspindle/monkey.py", line 2, in <module>
    import github3.gists
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/__init__.py", line 20, in <module>
    from .api import *
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/api.py", line 11, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/github.py", line 15, in <module>
    from .gists import Gist
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/gists/__init__.py", line 16, in <module>
    from .gist import Gist
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/gists/gist.py", line 14, in <module>
    from .comment import GistComment
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/gists/comment.py", line 12, in <module>
    from ..users import User
  File "/home/esc/.sysvenv2/local/lib/python2.7/site-packages/github3/users.py", line 12, in <module>
    from uritemplate import URITemplate
ImportError: No module named uritemplate
```

But maybe this should be reported upstream for `github3`?

**Comment by seveas** [comment]
Hmm, I don't think there's a bug here: github3 declares its dependencies properly. Though the uritemplate and uritemplate.py projects did merge this year, so some dependency confusion may hev areisen temporarily. In any case: not a git-spindle bug.
