### ISSUE TITLE
Can't add github account, gets "403 Cookies must be enabled"

### ISSUE THREAD

**Issue by mattiasb** [seveas/git-spindle#177]
With a freshly updated Python 2 `git-spindle`:
```shell
$ git hub add-account --host=https://github.com default
GitHub user: mattiasb 
GitHub password: 
Traceback (most recent call last):
  File "/home/mattiasb/.local/bin/git-hub", line 11, in <module>
    load_entry_point('git-spindle==3.4.4', 'console_scripts', 'git-hub')()
  File "/home/mattiasb/.local/lib/python2.7/site-packages/gitspindle/__init__.py", line 661, in hub
    GitHub().main()
  File "/home/mattiasb/.local/lib/python2.7/site-packages/gitspindle/__init__.py", line 473, in main
    func(opts)
  File "/home/mattiasb/.local/lib/python2.7/site-packages/gitspindle/__init__.py", line 486, in add_account
    self.login()
  File "/home/mattiasb/.local/lib/python2.7/site-packages/gitspindle/github.py", line 52, in login
    auth = self.gh.authorize(user, password, scopes, name, "http://seveas.github.com/git-spindle")
  File "/home/mattiasb/.local/lib/python2.7/site-packages/github3/github.py", line 121, in authorize
    json = self._json(self._post(url, data=data), 201)
  File "/home/mattiasb/.local/lib/python2.7/site-packages/github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "/home/mattiasb/.local/lib/python2.7/site-packages/github3/models.py", line 121, in _boolean
    raise GitHubError(response)
github3.models.GitHubError: 403 Cookies must be enabled to use GitHub.
```

**Comment by seveas** [comment]
Interesting. Do you also get this when just running 'git hub whoami' when you have no accounts configured?

**Comment by mattiasb** [comment]
No `git hub whoami` works fine regardless of whether I have an account configured or not.
