### ISSUE TITLE
"git hub fork cool-RR/PySnooper" throws an error

### ISSUE THREAD

**Issue by shlomif** [seveas/git-spindle#185]
```
git hub fork cool-RR/PySnooper
Traceback (most recent call last):
  File "/home/shlomif/.local/bin/git-hub", line 11, in <module>
    load_entry_point('git-spindle==3.4.4', 'console_scripts', 'git-hub')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/shlomif/.local/lib/python3.7/site-packages/gitspindle/__init__.py", line 1, in <module>
    import gitspindle.monkey
  File "/home/shlomif/.local/lib/python3.7/site-packages/gitspindle/monkey.py", line 11, in <module>
    github3.gists.gist._Gist.ssh_url = property(lambda self: 'git@gist.github.com:/%s.git' % self.id)
AttributeError: module 'github3.gists.gist' has no attribute '_Gist'
[shlomif@telaviv1 ~]$
```

Regards,

@shlomif

**Comment by shlomif** [comment]
The problem is gone after I did `pip3 install --upgrade --user --force .` from the git spindle's git master, but it should be updated in https://pypi.org/project/git-spindle/ too.
