### ISSUE TITLE
Give nicer error when trying to use a nonexistent repo:

### ISSUE THREAD

**Issue by seveas** [seveas/git-spindle#59]
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 5, in <module>
    GitHub().main()
  File "/usr/lib/python2.7/dist-packages/gitspindle/__init__.py", line 215, in main
    func(opts)
  File "/usr/lib/python2.7/dist-packages/gitspindle/github.py", line 477, in issue
    #""" % (repo.owner.login, repo.name)
AttributeError: 'NoneType' object has no attribute 'owner'

**Comment by seveas** [comment]
Fixed in 2.4
