### ISSUE TITLE
I broke set-origin again

### ISSUE THREAD

**Issue by seveas** [seveas/git-spindle#61]
dennis@spirit:~/code$ git hub clone git-jokes
Cloning into 'git-jokes'...
remote: Counting objects: 115, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 115 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (115/115), 40.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (33/33), done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 5, in <module>
    GitHub().main()
  File "/usr/lib/python2.7/dist-packages/gitspindle/__init__.py", line 215, in main
    func(opts)
  File "/usr/lib/python2.7/dist-packages/gitspindle/github.py", line 336, in clone
    self.set_origin(opts)
  File "/usr/lib/python2.7/dist-packages/gitspindle/github.py", line 968, in set_origin
    if self.git('config', 'remote.origin.url').stdout.strip() != repo.url:
AttributeError: 'Repository' object has no attribute 'url'

**Comment by seveas** [comment]
Fixed in 2.4
