### ISSUE TITLE
git-* repos errors out when not having any repos

### ISSUE THREAD

**Issue by seveas** [seveas/git-spindle#69]
Traceback (most recent call last):
  File "/home/dennis/code/git-spindle/bin/git-lab", line 5, in <module>
      GitLab().main()
        File "/home/dennis/code/git-spindle/lib/gitspindle/__init__.py", line 229, in main
            func(opts)
              File "/home/dennis/code/git-spindle/lib/gitspindle/gitlab.py", line 544, in repos
                  maxlen = max([len(x.name) for x in repos])
                  ValueError: max() arg is an empty sequence

**Comment by seveas** [comment]
Fixed in 2.4
