### ISSUE TITLE
git hub operations fail with TypeError: user() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by davidfraser** [seveas/git-spindle#85]
```
Traceback (most recent call last):
  File "bin/git-hub", line 11, in <module>
    GitHub().main()
  File "local/lib/python2.7/site-packages/gitspindle/__init__.py", line 243, in main
    self.login()
  File "local/lib/python2.7/site-packages/gitspindle/github.py", line 70, in login
    self.me = self.gh.user()
TypeError: user() takes exactly 2 arguments (1 given)
```
I think that should be `self.gh.user(user)`

**Comment by davidfraser** [comment]
`pip freeze` shows `github3.py==1.0.0a2`

**Comment by seveas** [comment]
Yeah, that won't work.  Try a non-alpha github3.py
Op 27 aug. 2015 14:46 schreef "David Fraser" <notifications@github.com>:

**Comment by davidfraser** [comment]
Whoops! Thanks...
